Numpy
----------------------

-> Supports 1D, 2D, and multi-dimensional arrays.<br>
-> NumPy arrays are generally (50 to 100 times) faster than Python lists for numerical operations and also takes less memory than lists.<br>
-> Provides functions for statistics, linear algebra, random numbers, etc.

In [3]:
import numpy as np

# one-dimentional array
arr1 = np.array([1, 2, 3, 4, 5])
print("One-dimensional array:")
print(arr1)

# two-dimentional array
arr2 = np.array([[1, 2, 3], 
                 [4, 5, 6]])
print("Two-dimensional array:")
print(arr2)

# multi-dimentional array
arr3 = np.array([[[1, 2], [3, 4]], 
                  [[5, 6], [7, 8]]])
print("Multi-dimensional array:")
print(arr3)

One-dimensional array:
[1 2 3 4 5]
Two-dimensional array:
[[1 2 3]
 [4 5 6]]
Multi-dimensional array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
# creating arrays from lists
list1 = [1, 2, 3, 4, 5]
arr_from_list = np.array(list1)
print("Array created from list:")
print(arr_from_list)

Array created from list:
[1 2 3 4 5]


In [10]:
# array with default values
zeros_array = np.zeros((2, 3))  # creates a 2x3 array filled with zeros
ones_array = np.ones((2, 3))   # creates a 2x3 array filled with ones
full_array = np.full((2, 3), 7)  # creates a 2x3 array filled with the value 7
identity_matrix = np.eye(3)  # creates a 3x3 identity matrix

print("Array of zeros:")
print(zeros_array)
print("Array of ones:")
print(ones_array)
print("Array filled with 7:")
print(full_array)
print("Identity matrix:")
print(identity_matrix)

Array of zeros:
[[0. 0. 0.]
 [0. 0. 0.]]
Array of ones:
[[1. 1. 1.]
 [1. 1. 1.]]
Array filled with 7:
[[7 7 7]
 [7 7 7]]
Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
# creating sequences of numbers
range_array = np.arange(0, 10, 2)  # (start, stop(exclusive), step)
print("Array with values from 0 to 10 (exclusive) with a step of 2:")
print(range_array)

Array with values from 0 to 10 (exclusive) with a step of 2:
[0 2 4 6 8]
