# Indexing

In [ ]:
import numpy as np

arr=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]])

print(arr[1,2]) 
print(arr[-1,-1])

8
15


# Slicing

In [7]:
# [start:stop(exclusive):step] 
# defaultvalues [0,len(arr),1]

print(arr[0:2, 1:4]) # Slicing rows 0 and 1, and columns 1 to 3
print()
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[1:4]) # Slicing elements from index 1 to 3
print(arr_1d[::2]) # Slicing every second element
print(arr_1d[::-1]) # Reversing the array

[[2 3 4]
 [7 8 9]]

[2 3 4]
[1 3 5]
[5 4 3 2 1]


# Fancy Indexcing
=> selecting multiple elements at once

In [8]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[[0, 2, 4]]) # Selecting elements at indices 0, 2, and 4

[1 3 5]


# Boolean Masking
=>Boolean masking is 10 time faster than for loop and if condition.

In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[arr > 2]) # Selecting elements greater than 2