# Reshaping 
-> changing dimentions with out changing data in it<br>
-> it does not creates a copy it just returns the view

In [2]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,9,10])
print("Original array:", arr)
print("Reshaped array (2x5):\n", arr.reshape(2, 5))

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Reshaped array (2x5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Flatening Array
-> used to convert multi dimentional array to 1d-array<br>
.ravel() -> view (Changes affect original array)<br>
.flatten() -> copy<br>

Note: both .ravel() and .flatten() wont changes the dimentions of original array

In [5]:
arr=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr.flatten()) # Flattening the 2D array to 1D
print(arr.ravel()) # Raveling the 2D array to 1D

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
