# Insert
np.insert(array, index, value, axis)<br>
array -> original array<br>
index -> position<br>
value -> data to be inserted<br>
axis=None -> then it is inserted into a flattened array<br>
axis=0 -> rowwise<br>
axis=1 -> column wise

In [2]:
import numpy as np 

arr=np.array([1,2,3,4,5])
print("Original array:", arr)
new_arr=np.insert( arr, 2, 100 ,axis=0)
print("New array after modification:", new_arr)

Original array: [1 2 3 4 5]
New array after modification: [  1   2 100   3   4   5]


In [3]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Original 2D array:\n", arr_2d)
new_arr_2d=np.insert(arr_2d, 1, [[10,11,12]], axis=0)
print("New 2D array after modification:\n", new_arr_2d)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
New 2D array after modification:
 [[ 1  2  3]
 [10 11 12]
 [ 4  5  6]
 [ 7  8  9]]


In [7]:
print("Original 2D array:\n", arr_2d)
new_arr_2d=np.insert(arr_2d, 1, [100,200,300], axis=1)
print("New 2D array after modification:\n", new_arr_2d)
new_arr_2d=np.insert(arr_2d, 1,[[111],[222],[333]], axis=1)
print("New 2D array after modification:\n", new_arr_2d)

Original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
New 2D array after modification:
 [[  1 100   2   3]
 [  4 200   5   6]
 [  7 300   8   9]]
New 2D array after modification:
 [[  1 111 222 333   2   3]
 [  4 111 222 333   5   6]
 [  7 111 222 333   8   9]]


# Append 
-> adding ele at the end of the array

In [8]:
arr=np.array([1,2,3,4,5])
new_arr=np.append(arr, [6,7,8])
print("Original array:", arr)
print("New array after modification:", new_arr)

Original array: [1 2 3 4 5]
New array after modification: [1 2 3 4 5 6 7 8]


# concatenate

np.concatenate((array1,array2),axis=0)<br>

axis=0 -> vertical stacking <br>
axis=1 -> horizontal stacking<br>

In [9]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([11,22,33,44,55])
new_arr=np.concatenate((arr1, arr2))
print("new_arr:", new_arr)

new_arr: [ 1  2  3  4  5 11 22 33 44 55]


# Delete 

np.delete(array, index, axis=None)

In [11]:
arr=np.array([10,20,30,40,50])
new_arr=np.delete(arr, 2)
print(arr)
print( new_arr)

[10 20 30 40 50]
[10 20 40 50]


In [14]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)
print()
new_arr_2d=np.delete(arr_2d, 1, axis=0)
print(new_arr_2d)
print()
new_arr_2d=np.delete(arr_2d, 1, axis=1)
print(new_arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [7 8 9]]

[[1 3]
 [4 6]
 [7 9]]


# Stacking

vertically / horizontally <br>

vstack() row wise<br>
hstack() column wise<br>

In [16]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])

print(np.vstack((arr1, arr2)))
print()
print(np.hstack((arr1, arr2)))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

[ 1  2  3  4  5  6  7  8  9 10]


# Spliting

np.split() equal <br>
np.hsplit() horizontally <br>
np.vsplit() vertically<br>

Note: if split size is not equal then it will give value error

In [18]:
arr=np.array([10,20,30,40,50,60,70,80,90,100])
print(np.split(arr,2)) 
print()
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(np.hsplit(arr_2d,3))
print()
print(np.vsplit(arr_2d,3))


[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]

[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
