# Broadcasting and Vectorization

Vectorization is the overarching goal of writing loop-free code, while broadcasting is a specific tool inside NumPy that makes vectorization possible when arrays do not match in size.<br>

->allows arithmetic operations to be performed on arrays of different shapes and sizes.

1. Mactching dimension<br>
[4,7,9]=[1,2,3]+[4,5,6]

2. Expanding single elements<br>
[11,12,13]=[1,2,3]+10

3. Incompatable shapes <br>
[1,2,3]+[1,2] -> error

In [5]:
import numpy as np

prices=np.array([100,200,300,400,500])

discount_up_on_all=prices*0.9
print(discount_up_on_all)
print()

matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
vector=np.array([10,20,30])
print(matrix+vector)

[ 90. 180. 270. 360. 450.]

[[11 22 33]
 [14 25 36]
 [17 28 39]]


### np.where()
np.where(condition, x, y) <br>
If True then x<br>
else y

np.where(condition)<br>
Returns: A tuple of arrays, where each array represents the indices along a specific axis (dimension) of the input.


In [7]:
discounted_prices=np.where(prices>300, prices*0.9, prices)
print(discounted_prices)
print()

arr=np.array([1,2,3,4,5])
print("Even Indices:", np.where(arr%2==0))

[100. 200. 300. 360. 450.]

Even Indices: (array([1, 3], dtype=int64),)


### np.select()

np.select(condlist, choicelist, default=0)<br>

-> Alternatives to 3-argument np.where<br>
-> Best for multiple, chained conditions (like an if-elif-else block). <br>
->  It evaluates an ordered list of conditions and matches them to a list of choices.

In [9]:
arr = np.array([5, 15, 25, 35])

conditions = [arr < 10, (arr >= 10) & (arr < 30), arr >= 30]
choices = ['Low', 'Medium', 'High']

# Cleans up nested np.where logic
result = np.select(conditions, choices, default='Unknown')
print(result)

['Low' 'Medium' 'Medium' 'High']


### np.clip()

A highly optimized shortcut if your np.where logic is just capping values at an upper or lower boundary.

In [10]:
arr = np.array([5, 12, 27, 45])

# Keeps values strictly between 10 and 30
result = np.clip(arr, 10, 30)
print(result)

[10 12 27 30]
