# Handling Missing Values

nan -> Not a Number
1. np.isnan()<br>
if (ele is nan) then True else False 

2. np.nan_t0_num() default value is 0<br>
it replaces nan with a number

In [6]:
import numpy as np

arr=np.array([1,2,np.nan,4,np.nan,6])
print(arr)
print(np.isnan(arr))

print(np.nan_to_num(arr, nan=0))

[ 1.  2. nan  4. nan  6.]
[False False  True False  True False]
[1. 2. 0. 4. 0. 6.]


3. np.isinf()<br>
if infinate then True else False
4. np.nan_to_num(array, posinf=1000, neginf=-1000)<br>
-> used to replace infinity with a number<br>
posinf -> Positive infinity<br>
neginf -> Negative infinity

In [ ]:
arr=np.array([1,2,np.inf,4,np.nan,6,-np.inf])
print(np.isinf(arr))

cleaned_arr = np.nan_to_num(arr, nan=0, posinf=9999, neginf=-9999)
print(cleaned_arr)

[False False  True False False False  True]
[ 1.000e+00  2.000e+00  9.999e+03  4.000e+00  0.000e+00  6.000e+00
 -9.999e+03]


#### Filtering Out Missing Values (Dropping Data)


In [ ]:
arr=np.array([1,2,np.nan,4,np.nan,6])
cleaned_arr = arr[~np.isnan(arr)]
print(cleaned_arr)

[1. 2. 4. 6.]


### Replacing Missing Values (Imputation)


In [12]:

# 1. np.where() and np.isnan() combination
arr=np.array([1.0,np.nan,3.0,np.nan,5.0])
# Replacing nan with 0.0
filled_arr=np.where(np.isnan(arr), 0.0, arr)
print(filled_arr)

#2. Direct Assignment
arr[np.isnan(arr)] = 0.0
print(arr)

#3. Using np.nan_to_num()
arr=np.array([1.0,np.nan,3.0,np.nan,5.0])
filled_arr=np.nan_to_num(arr, nan=0.0)
print(filled_arr)

[1. 0. 3. 0. 5.]
[1. 0. 3. 0. 5.]
[1. 0. 3. 0. 5.]


### Math Operations via nan safe funtions
1. Standard Function (Returns nan)  <br>
 np.sum(arr)                     <br>
 np.mean(arr)                     <br>
 np.std(arr)                     <br>
 np.min(arr) / np.max(arr)         <br>
 np.argmin(arr) / np.argmax(arr)<br>

2. NaN-Safe Alternative (Ignores nan)<br>
np.nansum(arr)<br>
np.nanmean(arr)<br>
np.nanstd(arr)<br>
np.nanmin(arr) / np.nanmax(arr)<br>
np.nanargmin(arr) / np.nanargmax(arr)<br>

In [16]:
arr=np.array([1,2,np.nan,4,np.nan,6])
arr[np.isnan(arr)]=np.nanmean(arr)
print(arr)

[1.   2.   3.25 4.   3.25 6.  ]
